dairy/urls.py
from django.conf.urls import url
from django.urls import path

from dairy import views
from dairy.views import DetailsAPIView

app_name = "dairy"

urlpatterns = [
    path('', views.index, name='index'),
    url('api/v1/details', DetailsAPIView.as_view(), name='details'),
]

djangoProjectbrodrick/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dairy.urls')),
]

dairy/models.py
from django.db import models

# Create your models here.

dairy/forms.py
from django import forms


class DateInput(forms.DateInput):
    input_type = 'date'


class InputForm(forms.Form):
    date = forms.DateTimeField(
        widget=DateInput()
    )
    prev_sales = forms.IntegerField()
    sales = forms.IntegerField()

dairy/views.py
from pathlib import Path

from flask import render_template
import sqlite3
import requests
from flask import Flask
import joblib
import pandas as pd
import os
import numpy as np
import json

from rest_framework import serializers
from rest_framework.generics import GenericAPIView
from rest_framework.response import Response
from tensorflow.keras.models import load_model
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Conv2D, Flatten, Dense
from sklearn.preprocessing import MinMaxScaler

BASE_DIR = Path(__file__).resolve().parent.parent

model = load_model("{}/files/my_model.h5".format(BASE_DIR))
model.summary()

from itertools import islice
from django.shortcuts import render

# Create your views here.
from dairy.forms import InputForm


class DetailsSerializer(serializers.Serializer):
    date = serializers.DateTimeField(format='%Y-%m-%d', input_formats=['%Y-%m-%d'])
    prev_sales = serializers.IntegerField()
    sales = serializers.IntegerField()


class DetailsAPIView(GenericAPIView):
    serializer_class = DetailsSerializer
    permission_classes = ()

    def get(self, request):
        # yourdata = [{"date": 10, "comments": 0}, {"likes": 4, "comments": 23}]
        # results = DetailsSerializer(yourdata, many=True).data
        # return Response(results)
        pass

    def post(self, request, format=None):
        print(request.data['date']+ " is the date")
        serializer_class = self.get_serializer_class()
        serializer = serializer_class(data=request.data, context={'request': request})
        serializer.is_valid(raise_exception=True)
        prediction = predict(request.data['date'],prev_sales=request.data['prev_sales'],Sales=request.data['sales'])
        data = prediction[0]
        print(data)
        return Response(data)


def slice_data_for_lstm(data, lookback):
    return np.array(
        list(zip(*[islice(np.array(data), i, None, 1) for i in range(lookback)]))
    )


def predict(date, prev_sales, Sales):
    date = str(date)
    prev_sales = float(prev_sales)
    Sales = float(Sales)
    diff = Sales - prev_sales

    print(date, prev_sales)

    # dictionary of lists
    dict = {
        "Week Ending Date": date,
        "Sales": Sales,
        "prev_sales": prev_sales,
        "diff": diff,
    }

    df = pd.DataFrame(dict, index=[0])
    print(df)

    new_dairy = df[["Week Ending Date", "Sales"]]

    df_supervised = df.drop(["prev_sales"], axis=1)
    print(df_supervised)

    # adding lags
    for inc in range(1, 13):
        field_name = "lag_" + str(inc)
        df_supervised[field_name] = df_supervised["diff"].shift(inc)

    # df_supervised = df_supervised.dropna().reset_index(drop=True)
    df_supervised = df_supervised.fillna(0)

    print(df_supervised)

    df_model = df_supervised.drop(["Sales", "Week Ending Date"], axis=1)

    test_set = df_model.values
    scaler = MinMaxScaler(feature_range=(-1, 1))

    scaler = scaler.fit(test_set)
    # reshape test set
    test_set = test_set.reshape(test_set.shape[0], test_set.shape[1])
    test_set_scaled = scaler.transform(test_set)

    test_set_scaled = scaler.transform(test_set)
    X_test, y_test = test_set_scaled[:, 1:], test_set_scaled[:, 0:1]
    X_test = X_test.reshape(X_test.shape[0], 1, X_test.shape[1])

    print(test_set)
    print(X_test)
    print(X_test.shape)

    y_pred = model.predict(X_test)
    print(y_pred)
    y_pred = y_pred.reshape(y_pred.shape[0], 1, y_pred.shape[1])

    pred_test_set = []
    for index in range(0, len(y_pred)):
        print(np.concatenate([y_pred[index], X_test[index]], axis=1))
        pred_test_set.append(np.concatenate([y_pred[index], X_test[index]], axis=1))

    # reshape pred_test_set
    pred_test_set = np.array(pred_test_set)
    pred_test_set = pred_test_set.reshape(
        pred_test_set.shape[0], pred_test_set.shape[2]
    )

    # inverse transform
    pred_test_set_inverted = scaler.inverse_transform(pred_test_set)
    print(pred_test_set_inverted)

    df_diff = new_dairy.copy()
    new_dairy.rename(columns={"Week Ending Date": "Date"}, inplace=True)

    # create dataframe that shows the predicted sales
    result_list = []
    sales_dates = list(new_dairy.Date)
    act_sales = list(new_dairy.Sales)

    for index in range(0, len(pred_test_set_inverted)):
        result_dict = {}
        result_dict["pred_value"] = int(
            pred_test_set_inverted[index][0] + act_sales[index]
        )
        result_dict["Date"] = sales_dates[index]
        result_list.append(result_dict)
    df_result = pd.DataFrame(result_list)
    print(df_result)

    return result_list


def index(request):
    form = InputForm()
    if request.method == "POST":
        form = InputForm(request.POST)
        context = {
            "form": form
        }
        # commit
        if form.is_valid():
            lst = predict(form.cleaned_data['date'], form.cleaned_data['prev_sales'], form.cleaned_data['sales'])
            context.update(lst[0])
            print(lst[0]['pred_value'], lst[0]['Date'])

        return render(request, 'panel.html', context)
    else:
        return render(request, 'panel.html', {'form': form})

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Prince & Broadrick {% block title_extension %}{% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {#    <link rel="icon" href="{% static 'images/favicon.ico' %} " type="image">#}
    <link href="https://fonts.googleapis.com/css?family=Poppins:200,300,400,500,600,700,800&display=swap"
          rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Amatic+SC:400,700&display=swap" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Yellowtail' rel='stylesheet'>
    <link rel="stylesheet" href="{% static 'css/open-iconic-bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">

    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css ' %}">
    <link rel="stylesheet" href="{% static 'fontawesome-pro/css/fontawesome.min.css' %}">

    <link rel="stylesheet" href="{% static 'css/aos.css' %}">

    <link rel="stylesheet" href="{% static 'css/ionicons.min.css' %}">

    <link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery.timepicker.css' %}">


    <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'css/icomoon.css ' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    {% block extra %}{% endblock %}
</head>
<body class="goto-here">


{% block maincontent %}



{% endblock %}


<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/jquery-migrate-3.0.1.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
<script src="{% static 'js/jquery.stellar.min.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'js/aos.js' %}"></script>
<script src="{% static 'js/jquery.animateNumber.min.js' %}"></script>
<script src="{% static 'js/bootstrap-datepicker.js' %}"></script>
<script src="{% static 'js/scrollax.min.js' %}"></script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
<script src="{% static 'js/google-map.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>

</body>
</html>

templates/panel.html
{% extends 'base.html' %}

{% load static %}
{% load crispy_forms_tags %}
{% block extra %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha/js/bootstrap.min.js"></script>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha/css/bootstrap.min.css" rel="stylesheet"/>

{% endblock %}
{% block title_extension %} Project Panel {% endblock %}
{% block maincontent %}
    <div class="container vh-100">
        <div class="card vh-100">
            <div class="row m-4 align-items-center">
                <form class="form-inline mb-lg-5 " action="{% url 'dairy:index' %}" method="post">
                    {% csrf_token %}
                    <div class="input-group  mr-2">
                        {{ form.date }}

                    </div>
                    <div class="input-group  mr-2">
                        {{ form.prev_sales }}

                    </div>
                    <div class="input-group  mr-2">
                        {{ form.sales }}

                    </div>

                    <button type="submit" class="btn btn-success btn-lg">Search</button>
                </form>
            </div>
   <div class="row">
               <p class="col-6">Predicted Value {{ pred_value }}</p><br>
               <p class="col-6">Date {{ Date }}</p>

            </div>
        </div>
    </div>
    <script>
        $(function () {
            $("#datetimepicker1").datetimepicker({
                format: 'DD/MM/YYYY HH:mm',
            });
        });
        $(function () {
            $("#datetimepicker2").datetimepicker({
                format: 'DD/MM/YYYY HH:mm',
            });
        });
    </script>
{% endblock %}
{% block footer %}{% endblock %}